packages:
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild

overrides:
  typescript: $typescript

peerDependencyRules:
  allowAny:
    - rollup
  ignoreMissing:
    - rollup
    - webpack
    - '@vue/compiler-sfc'
